In [1]:
import os
import shutil
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("QSLR2024/annotations/manual/video_title_qslr2024.csv")
print("Jumlah data:", len(df))
df.head()

Jumlah data: 361

,id,video_name,signer,gloss,word,text
0,1,1_alfatihah_1_1_1.mp4,signer-1,bi s mi allā hi rra ḥ mā ni rra ḥī m,bismi allāhi rraḥmāni rraḥīm,bismillāhirraḥmānirraḥīm
1,2,1_alfatihah_2_1_1.mp4,signer-2,bi s mi allā hi rra ḥ mā ni rra ḥī m,bismi allāhi rraḥmāni rraḥīm,bismillāhirraḥmānirraḥīm
2,3,1_alfatihah_3_1_1.mp4,signer-3,bi s mi allā hi rra ḥ mā ni rra ḥī m,bismi allāhi rraḥmāni rraḥīm,bismillāhirraḥmānirraḥīm
3,14,1_alfatihah_1_1_2.mp4,signer-1,bi s mi allā hi rra ḥ mā ni rra ḥī m,bismi allāhi rraḥmāni rraḥīm,bismillāhirraḥmānirraḥīm
4,15,1_alfatihah_1_1_3.mp4,signer-1,bi s mi allā hi rra ḥ mā ni rra ḥī m,bismi allāhi rraḥmāni rraḥīm,bismillāhirraḥmānirraḥīm

In [3]:
df = df.drop(['id', 'word', 'text'], axis=1)
df['video_name'] = df['video_name'].str.replace('.mp4', '', regex=False)
df['folder'] = df['video_name'] + "/*.jpg"

In [4]:
df.rename(columns={'video_name': 'id'}, inplace=True)
df.rename(columns={'gloss': 'annotation'}, inplace=True)

In [5]:
df.head()

,id,signer,annotation,folder
0,1_alfatihah_1_1_1,signer-1,bi s mi allā hi rra ḥ mā ni rra ḥī m,1_alfatihah_1_1_1/*.jpg
1,1_alfatihah_2_1_1,signer-2,bi s mi allā hi rra ḥ mā ni rra ḥī m,1_alfatihah_2_1_1/*.jpg
2,1_alfatihah_3_1_1,signer-3,bi s mi allā hi rra ḥ mā ni rra ḥī m,1_alfatihah_3_1_1/*.jpg
3,1_alfatihah_1_1_2,signer-1,bi s mi allā hi rra ḥ mā ni rra ḥī m,1_alfatihah_1_1_2/*.jpg
4,1_alfatihah_1_1_3,signer-1,bi s mi allā hi rra ḥ mā ni rra ḥī m,1_alfatihah_1_1_3/*.jpg

In [6]:
# Mengatur ulang urutan kolom menggunakan reindex
df = df.reindex(columns=['id', 'folder', 'signer', 'annotation'])

In [7]:
df.head()

,id,folder,signer,annotation
0,1_alfatihah_1_1_1,1_alfatihah_1_1_1/*.jpg,signer-1,bi s mi allā hi rra ḥ mā ni rra ḥī m
1,1_alfatihah_2_1_1,1_alfatihah_2_1_1/*.jpg,signer-2,bi s mi allā hi rra ḥ mā ni rra ḥī m
2,1_alfatihah_3_1_1,1_alfatihah_3_1_1/*.jpg,signer-3,bi s mi allā hi rra ḥ mā ni rra ḥī m
3,1_alfatihah_1_1_2,1_alfatihah_1_1_2/*.jpg,signer-1,bi s mi allā hi rra ḥ mā ni rra ḥī m
4,1_alfatihah_1_1_3,1_alfatihah_1_1_3/*.jpg,signer-1,bi s mi allā hi rra ḥ mā ni rra ḥī m

In [8]:
# Membagi dataset menjadi train (80%) dan sisa (20%)
train_df, temp_df = train_test_split(df, test_size=0.1, random_state=42)

In [9]:
# Membagi sisa dataset menjadi dev dan test (masing-masing 50% dari 20%, sehingga 10% dari total untuk masing-masing)
dev_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=42)

In [10]:
# Menampilkan jumlah baris untuk memastikan pembagian
print("Jumlah data train:", len(train_df))
print("Jumlah data dev:", len(dev_df))
print("Jumlah data test:", len(test_df))

Jumlah data train: 324
Jumlah data dev: 18
Jumlah data test: 19

In [11]:
train_df.head()

,id,folder,signer,annotation
22,1_alfatihah_3_1_3,1_alfatihah_3_1_3/*.jpg,signer-3,bi s mi allā hi rra ḥ mā ni rra ḥī m
298,112_alikhlas_1_3_3,112_alikhlas_1_3_3/*.jpg,signer-1,la m ya li d wa la m yū la d
173,1_alfatihah_2_5_7,1_alfatihah_2_5_7/*.jpg,signer-2,i yyā ka na ' bu du wa i yyā ka na s ta 'ī n
240,1_alfatihah_1_7b_4,1_alfatihah_1_7b_4/*.jpg,signer-1,ga i ri l ma g ḍū bi ‘a la i hi m wa la ḍḍā llī n
344,112_alikhlas_2_4_3,112_alikhlas_2_4_3/*.jpg,signer-2,Wa la m ya ku l la hū ku fu wa n a ḥa d

In [12]:
# Asumsikan DataFrame 'df' sudah dimuat seperti contoh sebelumnya
# Tentukan lokasi tujuan kemana folder akan dipindahkan
destination_path = 'QSLR2024/features/fullFrame-480x480px/test/'

In [13]:
if not os.path.exists(destination_path):
    os.makedirs(destination_path )

In [14]:
# Iterasi melalui DataFrame
for index, row in test_df.iterrows():
    # Asal folder (anda perlu menyesuaikan ini jika lokasi lengkap tidak terdefinisi di DataFrame)
    source_folder = row['id']
    source_folder = os.path.join('QSLR2024/features/fullFrame-480x480px/', source_folder)
    
    # Lokasi tujuan penuh
    full_destination_path = row['id']
    full_destination_path = os.path.join(destination_path,  full_destination_path)

    # Pindahkan folder jika folder asal ada
    if os.path.exists(source_folder):
        shutil.move(source_folder, full_destination_path)
        print(f"Folder {row['id']} telah dipindahkan ke {full_destination_path}")
    else:
        print(f"Folder {row['id']} tidak ditemukan di {source_folder}")

Folder 1_alfatihah_2_7a_8 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/1_alfatihah_2_7a_8
Folder 1_alfatihah_3_2_8 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/1_alfatihah_3_2_8
Folder 1_alfatihah_3_2_9 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/1_alfatihah_3_2_9
Folder 112_alikhlas_3_4_6 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/112_alikhlas_3_4_6
Folder 1_alfatihah_3_3_6 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/1_alfatihah_3_3_6
Folder 1_alfatihah_2_6_9 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/1_alfatihah_2_6_9
Folder 112_alikhlas_2_1_8 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/112_alikhlas_2_1_8
Folder 1_alfatihah_2_7a_2 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/1_alfatihah_2_7a_2
Folder 112_alikhlas_1_4_3 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/112_alikhlas_1_4_3
Folder 1_alfatihah_2_7b_9 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/1_alfatihah_2_7b_9
Folder 112_alikhlas_1_2_1 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/112_alikhlas_1_2_1
Folder 1_alfatihah_3_6_3 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/1_alfatihah_3_6_3
Folder 1_alfatihah_3_7a_6 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/1_alfatihah_3_7a_6
Folder 1_alfatihah_2_2_3 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/1_alfatihah_2_2_3
Folder 1_alfatihah_1_4_9 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/1_alfatihah_1_4_9
Folder 1_alfatihah_2_3_1 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/1_alfatihah_2_3_1
Folder 1_alfatihah_3_5_7 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/1_alfatihah_3_5_7
Folder 1_alfatihah_2_3_9 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/1_alfatihah_2_3_9
Folder 1_alfatihah_1_6_7 tidak ditemukan di QSLR2024/features/fullFrame-480x480px/1_alfatihah_1_6_7

In [15]:
train_df.to_csv('QSLR2024/annotations/manual/train.corpus.csv',encoding='utf-8', sep='|', index=False)
dev_df.to_csv('QSLR2024/annotations/manual/dev.corpus.csv',encoding='utf-8', sep='|', index=False)
test_df.to_csv('QSLR2024/annotations/manual/test.corpus.csv', encoding='utf-8', sep='|', index=False)

In [ ]:
../dataset/QSLR2024/features/fullFrame-480x480
train/1_alfatihah_1_4_4/*.jpg
../dataset/QSLR2024/features/fullFrame-480x480
../dataset/QSLR2024/features/fullFrame-480x480
../dataset/QSLR2024/features/fullFrame-480x480
../dataset/QSLR2024/features/fullFrame-480x480
train/112_alikhlas_3_4_10/*.jpg
[]
train/1_alfatihah_2_3_7/*.jpg
../dataset/QSLR2024/features/fullFrame-480x480
train/1_alfatihah_2_1_9/*.jpg
train/112_alikhlas_2_1_3/*.jpg
train/1_alfatihah_2_6_3/*.jpg
../dataset/QSLR2024/features/fullFrame-480x480

In [2]:
import glob

In [3]:
img_list = glob.glob("../dataset/QSLR2024/features/fullFrame-480x480"+"/"+"train/1_alfatihah_1_4_4/*.jpg")

In [4]:
img_list

[]